const moviesTestDB = [
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '1',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '2',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '3',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '4',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '5',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '6',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '7',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '8',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '9',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '10',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '11',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '12',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '13',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '14',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '15',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
  {
    country: 'Россия',
    director: 'test',
    duration: '145',
    year: '2023',
    description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos odio quae tempora aperiam itaque consequatur similique ea placeat aliquid minima.',
    image: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    trailerLink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail: 'https://cdn.create.vista.com/api/media/medium/228985366/stock-photo-stereoscopic-glasses-popcorn-cubes-cinema-lettering-isolated-yellow?token=',
    movieId: '16',
    nameRU: 'ТЕСТ',
    nameEN: 'TEST',
  },
];

export default moviesTestDB;